services:
  postgres:
    image: postgres:16
    container_name: botverse-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    # ⚠️ Проброс порта нужен только для локальной разработки.
    # В проде удалить "5432:5432", чтобы не открывать базу наружу!
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres-data:/var/lib/postgresql/data
