version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: botverse-postgres
    restart: always
    env_file:
      - .env

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "6432:5432"
    volumes:
      - botverse_data:/var/lib/postgresql/data

volumes:
  botverse_data:
